@server = https://opulent-eureka-qjrgqxvgxqgfx7v9-8080.app.github.dev
###
GET {{server}}/api/empleados 
###
POST {{server}}/api/empleados
Content-Type: application/json

{"nombre": "Juan", "correo": "ju@gml.p"}

###
GET {{server}}/api/proyectos 
###
POST {{server}}/api/proyectos
Content-Type: application/json

{"nombre": "Desarrollo de planos", "descripcion": "desarrollo de planos para una planta baja"}